//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace quiz {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("quiz.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   を ↓ から えらんでね に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageQuiz {
            get {
                return ResourceManager.GetString("ImageQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ページ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ひらがな に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainButton1 {
            get {
                return ResourceManager.GetString("MainButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタカナ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainButton2 {
            get {
                return ResourceManager.GetString("MainButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ENGLISH に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainButton3 {
            get {
                return ResourceManager.GetString("MainButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ずかん に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainButton4 {
            get {
                return ResourceManager.GetString("MainButton4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   なまえを ↓ から えらんでね に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameQuiz {
            get {
                return ResourceManager.GetString("NameQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   けっか に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   もういちど に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   なまえあてクイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubButton1 {
            get {
                return ResourceManager.GetString("SubButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   イラストあてクイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubButton2 {
            get {
                return ResourceManager.GetString("SubButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あなうめクイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubButton3 {
            get {
                return ResourceManager.GetString("SubButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ○×クイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubButton4 {
            get {
                return ResourceManager.GetString("SubButton4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   うみのいきものクイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
